version: 2.1

executors:
  default:
    docker:
      - image: quay.io/hemanth22/rockylinux9:9

jobs:
  build:
    executor: default
    steps:
      - checkout
      - run:
          name: Print Python Verson
          command: |
            dnf install python3-pip -y
            python3 -V
            python3 -m pip install requests
      - run:
          name: Send Message notification to OpenShift
          command: |
            python3 fastapi_notify.py
      - run:
          name: Send Message notification to OpenShift Serverless Function
          command: |
            python3 fastapi_notify_water.py
      - run:
          name: Timesheet alert
          command: |
            python3 fastapi_timesheet.py

workflows:
  notify_app:
    jobs:
      - build
    triggers:
      - schedule:
          cron: "0 3,4,5,6,7,8,9,10,11,12,13,14,15,16,17 * * *"
          filters:
            branches:
              only:
                - main
